name = "glemail"
version = "0.1.0"
description = "A lightweight request wrapper for various email providers"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Ramkarthik", repo = "glemail" }
links = [{ title = "Website", href = "https://kramkarthik.com" }, { title = "Twitter", href = "https://x.com/Ramkarthik" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
